"""Canonical token and file-target mapping definitions."""

from __future__ import annotations

CANONICAL_TOKENS: tuple[str, ...] = (
    "background",
    "foreground",
    "accent",
    "cursor",
    "selection_background",
    "selection_foreground",
    "active_border_color",
    "color0",
    "color1",
    "color2",
    "color3",
    "color4",
    "color5",
    "color6",
    "color7",
    "color8",
    "color9",
    "color10",
    "color11",
    "color12",
    "color13",
    "color14",
    "color15",
)

SYNC_TARGET_FILES: tuple[str, ...] = (
    "alacritty.toml",
    "kitty.conf",
    "ghostty.conf",
    "colors.css",
    "aether.override.css",
    "gtk.css",
    "hyprland.conf",
    "hyprlock.conf",
    "btop.theme",
    "chromium.theme",
    "neovim.lua",
    "aether.zed.json",
    "vencord.theme.css",
    "wofi.css",
    "warp.yaml",
    "walker.css",
    "waybar.css",
    "mako.ini",
    "swayosd.css",
)

ALACRITTY_FIELD_MAP: dict[str, tuple[str, str]] = {
    "background": ("colors.primary", "background"),
    "foreground": ("colors.primary", "foreground"),
    "cursor": ("colors.cursor", "cursor"),
    "selection_background": ("colors.selection", "background"),
    "selection_foreground": ("colors.selection", "text"),
    "color0": ("colors.normal", "black"),
    "color1": ("colors.normal", "red"),
    "color2": ("colors.normal", "green"),
    "color3": ("colors.normal", "yellow"),
    "color4": ("colors.normal", "blue"),
    "color5": ("colors.normal", "magenta"),
    "color6": ("colors.normal", "cyan"),
    "color7": ("colors.normal", "white"),
    "color8": ("colors.bright", "black"),
    "color9": ("colors.bright", "red"),
    "color10": ("colors.bright", "green"),
    "color11": ("colors.bright", "yellow"),
    "color12": ("colors.bright", "blue"),
    "color13": ("colors.bright", "magenta"),
    "color14": ("colors.bright", "cyan"),
    "color15": ("colors.bright", "white"),
}

KITTY_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "cursor": "cursor",
    "selection_background": "selection_background",
    "selection_foreground": "selection_foreground",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}

GHOSTTY_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "color0": "0",
    "color1": "1",
    "color2": "2",
    "color3": "3",
    "color4": "4",
    "color5": "5",
    "color6": "6",
    "color7": "7",
    "color8": "8",
    "color9": "9",
    "color10": "10",
    "color11": "11",
    "color12": "12",
    "color13": "13",
    "color14": "14",
    "color15": "15",
}

CSS_VARIABLE_MAP: dict[str, str] = {
    "background": "--background",
    "foreground": "--foreground",
    "cursor": "--cursor",
    "selection_background": "--selection-background",
    "selection_foreground": "--selection-foreground",
    "color0": "--color0",
    "color1": "--color1",
    "color2": "--color2",
    "color3": "--color3",
    "color4": "--color4",
    "color5": "--color5",
    "color6": "--color6",
    "color7": "--color7",
    "color8": "--color8",
    "color9": "--color9",
    "color10": "--color10",
    "color11": "--color11",
    "color12": "--color12",
    "color13": "--color13",
    "color14": "--color14",
    "color15": "--color15",
}

CSS_DEFINE_COLOR_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "accent": "accent",
    "cursor": "cursor",
    "selection_background": "selection_bg",
    "selection_foreground": "selection_fg",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}

HYPRLAND_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "accent": "accent",
    "cursor": "cursor",
    "selection_background": "selection_background",
    "selection_foreground": "selection_foreground",
    "active_border_color": "activeBorderColor",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}

BTOP_FIELD_MAP: dict[str, tuple[str, ...]] = {
    "background": ("theme[main_bg]",),
    "foreground": ("theme[main_fg]", "theme[selected_fg]"),
    "color5": (
        "theme[title]",
        "theme[proc_misc]",
    ),
    "color6": ("theme[hi_fg]",),
    "color2": ("theme[cpu_box]", "theme[mem_box]", "theme[net_box]", "theme[proc_box]"),
    "color8": ("theme[selected_bg]", "theme[inactive_fg]", "theme[div_line]"),
}

CHROMIUM_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "accent": "accent",
    "selection_background": "selection_background",
    "selection_foreground": "selection_foreground",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}

NEOVIM_LUA_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "background": ("bg", "bg_dark"),
    "color8": ("bg_highlight", "comment"),
    "foreground": ("fg", "fg_dark"),
    "color1": ("red",),
    "color9": ("orange",),
    "color3": ("yellow",),
    "color2": ("green",),
    "color6": ("cyan",),
    "color4": ("blue",),
    "color5": ("purple",),
    "color13": ("magenta",),
}

WALKER_CSS_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "accent": ("selected-text",),
    "foreground": ("text", "foreground"),
    "background": ("base", "background"),
    "color8": ("border",),
}

WAYBAR_CSS_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "background": ("background",),
    "foreground": ("foreground",),
    "accent": ("accent",),
    "cursor": ("cursor",),
    "selection_background": ("selection_bg",),
    "selection_foreground": ("selection_fg",),
    "active_border_color": ("active_border_color", "active-border-color", "border_focus"),
    "color0": ("color0",),
    "color1": ("color1",),
    "color2": ("color2",),
    "color3": ("color3",),
    "color4": ("color4",),
    "color5": ("color5",),
    "color6": ("color6",),
    "color7": ("color7",),
    "color8": ("color8",),
    "color9": ("color9",),
    "color10": ("color10",),
    "color11": ("color11",),
    "color12": ("color12",),
    "color13": ("color13",),
    "color14": ("color14",),
    "color15": ("color15",),
}

MAKO_INI_COLOR_MAP: dict[str, str] = {
    "foreground": "text-color",
    "color5": "border-color",
    "background": "background-color",
}

SWAYOSD_CSS_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "background": ("background-color",),
    "color8": ("border-color",),
    "foreground": ("label", "image"),
    "color3": ("progress",),
}

HYPRLOCK_FIELD_MAP: dict[str, tuple[str, ...]] = {
    "background": ("color", "inner_color"),
    "color5": ("outer_color",),
    "foreground": ("font_color", "placeholder_color"),
    "color6": ("check_color",),
}

GTK_CSS_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "background": ("background",),
    "foreground": ("foreground",),
    "color0": ("black",),
    "color1": ("red",),
    "color2": ("green",),
    "color3": ("yellow",),
    "color4": ("blue",),
    "color5": ("magenta",),
    "color6": ("cyan",),
    "color7": ("white",),
    "color8": ("bright_black",),
    "color9": ("bright_red",),
    "color10": ("bright_green",),
    "color11": ("bright_yellow",),
    "color12": ("bright_blue",),
    "color13": ("bright_magenta",),
    "color14": ("bright_cyan",),
    "color15": ("bright_white",),
}

VENCORD_CSS_COLOR_MAP: dict[str, str] = {
    "color0": "--color00",
    "color1": "--color01",
    "color2": "--color02",
    "color3": "--color03",
    "color4": "--color04",
    "color5": "--color05",
    "color6": "--color06",
    "color7": "--color07",
    "color8": "--color08",
    "color9": "--color09",
    "color10": "--color10",
    "color11": "--color11",
    "color12": "--color12",
    "color13": "--color13",
    "color14": "--color14",
    "color15": "--color15",
}

WOFI_CSS_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "background": ("bg",),
    "foreground": ("fg",),
    "color2": ("gray1",),
    "color8": ("gray2",),
    "color4": ("gray3",),
    "color3": ("gray4",),
    "color5": ("gray5",),
    "color15": ("fg_bright",),
}

WARP_YAML_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "accent": ("accent",),
    "cursor": ("cursor",),
    "background": ("background",),
    "foreground": ("foreground",),
    "color0": ("normal.black",),
    "color1": ("normal.red",),
    "color2": ("normal.green",),
    "color3": ("normal.yellow",),
    "color4": ("normal.blue",),
    "color5": ("normal.magenta",),
    "color6": ("normal.cyan",),
    "color7": ("normal.white",),
    "color8": ("bright.black",),
    "color9": ("bright.red",),
    "color10": ("bright.green",),
    "color11": ("bright.yellow",),
    "color12": ("bright.blue",),
    "color13": ("bright.magenta",),
    "color14": ("bright.cyan",),
    "color15": ("bright.white",),
}

AETHER_OVERRIDE_CSS_COLOR_MAP: dict[str, tuple[str, ...]] = {
    "background": ("background",),
    "foreground": ("foreground",),
    "color0": ("black",),
    "color1": ("red",),
    "color2": ("green",),
    "color3": ("yellow",),
    "color4": ("blue",),
    "color5": ("magenta",),
    "color6": ("cyan",),
    "color7": ("white",),
    "color8": ("bright_black",),
    "color9": ("bright_red",),
    "color10": ("bright_green",),
    "color11": ("bright_yellow",),
    "color12": ("bright_blue",),
    "color13": ("bright_magenta",),
    "color14": ("bright_cyan",),
    "color15": ("bright_white",),
}

AETHER_ZED_STYLE_COLOR_MAP: dict[str, str] = {
    "border": "background",
    "border.variant": "background",
    "elevated_surface.background": "background",
    "surface.background": "background",
    "background": "background",
    "element.background": "color8",
    "element.hover": "background",
    "element.selected": "background",
    "drop_target.background": "background",
    "ghost_element.hover": "color8",
    "ghost_element.selected": "background",
    "text": "foreground",
    "text.muted": "foreground",
    "text.placeholder": "foreground",
    "text.disabled": "background",
    "text.accent": "color6",
    "status_bar.background": "background",
    "title_bar.background": "background",
    "title_bar.inactive_background": "color8",
    "toolbar.background": "background",
    "tab_bar.background": "background",
    "tab.inactive_background": "color8",
    "tab.active_background": "background",
    "search.match_background": "background",
    "panel.background": "background",
    "panel.focused_border": "background",
    "scrollbar.thumb.background": "background",
    "scrollbar.thumb.hover_background": "color8",
    "scrollbar.track.background": "background",
    "editor.foreground": "foreground",
    "editor.background": "background",
    "editor.gutter.background": "background",
    "editor.subheader.background": "background",
    "editor.active_line.background": "color8",
    "editor.line_number": "color8",
    "editor.active_line_number": "foreground",
    "editor.wrap_guide": "color8",
    "editor.active_wrap_guide": "color8",
    "editor.document_highlight.read_background": "color8",
    "editor.document_highlight.write_background": "color8",
    "terminal.background": "background",
    "terminal.ansi.black": "color0",
    "terminal.ansi.bright_black": "color8",
    "terminal.ansi.red": "color1",
    "terminal.ansi.bright_red": "color9",
    "terminal.ansi.green": "color2",
    "terminal.ansi.bright_green": "color10",
    "terminal.ansi.yellow": "color3",
    "terminal.ansi.bright_yellow": "color11",
    "terminal.ansi.blue": "color4",
    "terminal.ansi.bright_blue": "color12",
    "terminal.ansi.magenta": "color5",
    "terminal.ansi.bright_magenta": "color13",
    "terminal.ansi.cyan": "color6",
    "terminal.ansi.bright_cyan": "color14",
    "terminal.ansi.white": "color7",
    "terminal.ansi.bright_white": "color15",
    "link_text.hover": "color6",
    "conflict": "color3",
    "conflict.background": "background",
    "conflict.border": "color3",
    "created": "color2",
    "created.background": "background",
    "created.border": "color2",
    "deleted": "color1",
    "deleted.background": "background",
    "deleted.border": "color1",
    "error": "color1",
    "error.background": "background",
    "error.border": "color1",
    "hidden": "color8",
    "hidden.background": "background",
    "hidden.border": "color8",
    "hint": "foreground",
    "hint.background": "background",
    "hint.border": "color6",
    "ignored": "color8",
    "ignored.background": "background",
    "ignored.border": "color8",
    "info": "color6",
    "info.background": "background",
    "info.border": "color6",
    "modified": "color4",
    "modified.background": "background",
    "modified.border": "color4",
    "predictive": "color8",
    "predictive.background": "color8",
    "predictive.border": "background",
    "renamed": "color3",
    "renamed.background": "background",
    "renamed.border": "color3",
    "success": "color2",
    "success.background": "background",
    "success.border": "color2",
    "unreachable": "color3",
    "unreachable.background": "background",
    "unreachable.border": "color3",
    "warning": "color3",
    "warning.background": "background",
    "warning.border": "color3",
}
