"""Canonical token and file-target mapping definitions."""

from __future__ import annotations

CANONICAL_TOKENS: tuple[str, ...] = (
    "background",
    "foreground",
    "accent",
    "cursor",
    "selection_background",
    "selection_foreground",
    "color0",
    "color1",
    "color2",
    "color3",
    "color4",
    "color5",
    "color6",
    "color7",
    "color8",
    "color9",
    "color10",
    "color11",
    "color12",
    "color13",
    "color14",
    "color15",
)

SYNC_TARGET_FILES: tuple[str, ...] = (
    "alacritty.toml",
    "kitty.conf",
    "colors.css",
    "hyprland.conf",
    "btop.theme",
    "chromium.theme",
)

ALACRITTY_FIELD_MAP: dict[str, tuple[str, str]] = {
    "background": ("colors.primary", "background"),
    "foreground": ("colors.primary", "foreground"),
    "cursor": ("colors.cursor", "cursor"),
    "selection_background": ("colors.selection", "background"),
    "selection_foreground": ("colors.selection", "text"),
    "color0": ("colors.normal", "black"),
    "color1": ("colors.normal", "red"),
    "color2": ("colors.normal", "green"),
    "color3": ("colors.normal", "yellow"),
    "color4": ("colors.normal", "blue"),
    "color5": ("colors.normal", "magenta"),
    "color6": ("colors.normal", "cyan"),
    "color7": ("colors.normal", "white"),
    "color8": ("colors.bright", "black"),
    "color9": ("colors.bright", "red"),
    "color10": ("colors.bright", "green"),
    "color11": ("colors.bright", "yellow"),
    "color12": ("colors.bright", "blue"),
    "color13": ("colors.bright", "magenta"),
    "color14": ("colors.bright", "cyan"),
    "color15": ("colors.bright", "white"),
}

KITTY_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "cursor": "cursor",
    "selection_background": "selection_background",
    "selection_foreground": "selection_foreground",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}

CSS_VARIABLE_MAP: dict[str, str] = {
    "background": "--background",
    "foreground": "--foreground",
    "cursor": "--cursor",
    "selection_background": "--selection-background",
    "selection_foreground": "--selection-foreground",
    "color0": "--color0",
    "color1": "--color1",
    "color2": "--color2",
    "color3": "--color3",
    "color4": "--color4",
    "color5": "--color5",
    "color6": "--color6",
    "color7": "--color7",
    "color8": "--color8",
    "color9": "--color9",
    "color10": "--color10",
    "color11": "--color11",
    "color12": "--color12",
    "color13": "--color13",
    "color14": "--color14",
    "color15": "--color15",
}

HYPRLAND_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "accent": "accent",
    "cursor": "cursor",
    "selection_background": "selection_background",
    "selection_foreground": "selection_foreground",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}

BTOP_FIELD_MAP: dict[str, str] = {
    "background": "theme[main_bg]",
    "foreground": "theme[main_fg]",
    "accent": "theme[title]",
    "selection_background": "theme[selected_bg]",
    "selection_foreground": "theme[selected_fg]",
    "color0": "theme[inactive_fg]",
    "color1": "theme[hi_fg]",
}

CHROMIUM_FIELD_MAP: dict[str, str] = {
    "background": "background",
    "foreground": "foreground",
    "accent": "accent",
    "selection_background": "selection_background",
    "selection_foreground": "selection_foreground",
    "color0": "color0",
    "color1": "color1",
    "color2": "color2",
    "color3": "color3",
    "color4": "color4",
    "color5": "color5",
    "color6": "color6",
    "color7": "color7",
    "color8": "color8",
    "color9": "color9",
    "color10": "color10",
    "color11": "color11",
    "color12": "color12",
    "color13": "color13",
    "color14": "color14",
    "color15": "color15",
}
